# Premiers Essais sur BERT

In [1]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

In [2]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

text = ("After Abraham Lincoln won the November 1860 presidential "
        "election on an anti-slavery platform, an initial seven "
        "slave states declared their secession from the country "
        "to form the Confederacy. War broke out in April 1861 "
        "when secessionist forces attacked Fort Sumter in South "
        "Carolina, just over a month after Lincoln's "
        "inauguration.")

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/420M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [3]:
inputs = tokenizer(text, return_tensors='pt')

In [4]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [5]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [7]:
inputs['labels'] = inputs.input_ids.detach().clone()

In [8]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([

In [9]:
# create random array of floats in equal dimension to input_ids
rand = torch.rand(inputs.input_ids.shape)
# where the random array is less than 0.15, we set true
mask_arr = rand < 0.15
mask_arr

tensor([[ True, False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False,  True, False, False, False, False,
          True, False, False, False, False, False, False, False,  True, False,
         False, False, False,  True,  True, False, False, False, False,  True,
         False, False,  True,  True, False, False, False, False,  True, False,
         False, False, False, False, False, False, False,  True,  True, False,
         False, False]])

In [29]:
(inputs.input_ids != 101) * (inputs.input_ids != 102)

tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True, False]])

In [30]:
mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
mask_arr

tensor([[False, False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False,  True, False, False, False, False,
          True, False, False, False, False, False, False, False,  True, False,
         False, False, False,  True,  True, False, False, False, False,  True,
         False, False,  True,  True, False, False, False, False,  True, False,
         False, False, False, False, False, False, False,  True,  True, False,
         False, False]])

In [31]:
# create selection from mask_arr
selection = torch.flatten((mask_arr[0]).nonzero()).tolist()
selection

[2, 15, 20, 28, 33, 34, 39, 42, 43, 48, 57, 58]

In [32]:
# apply selection index to inputs.input_ids, adding MASK tokens
inputs.input_ids[0, selection] = 103

In [33]:
inputs

{'input_ids': tensor([[  101,  2044,   103,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,   103,  1010,  2019,  3988,  2698,
           103,  2163,  4161,  2037, 22965,  2013,  1996,  2406,   103,  2433,
          1996, 18179,  1012,   103,   103,  2041,  1999,  2258,  6863,   103,
         22965,  2923,   103,   103,  3481,  7680,  3334,  1999,   103,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,   103,   103, 17331,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([

In [38]:
# pass inputs as kwarg to model
outputs = model(**inputs)

In [39]:
outputs

MaskedLMOutput(loss=tensor(1.0133, grad_fn=<NllLossBackward0>), logits=tensor([[[ -6.9043,  -6.8299,  -6.8807,  ...,  -6.1494,  -5.9478,  -4.2728],
         [ -7.5747,  -7.4835,  -7.5942,  ...,  -7.1913,  -7.0748,  -6.4572],
         [ -6.5147,  -6.9016,  -6.3663,  ...,  -6.7512,  -5.9587,  -8.2238],
         ...,
         [ -4.5714,  -4.6684,  -4.5395,  ...,  -4.2798,  -3.5413,  -6.6445],
         [-14.0347, -13.9381, -14.0201,  ..., -10.8364, -11.1594,  -9.2289],
         [-12.1673, -12.5205, -12.1467,  ..., -11.7206,  -9.8209,  -9.6739]]],
       grad_fn=<AddBackward0>), hidden_states=None, attentions=None)

In [40]:
# we get two output tensors, loss and logits
outputs.keys()

odict_keys(['loss', 'logits'])

In [41]:
outputs.loss

tensor(1.0133, grad_fn=<NllLossBackward0>)

In [42]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [47]:
output.last_hidden_state[0].shape

torch.Size([12, 768])

## test

In [83]:
import os
import shutil

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from official.nlp import optimization  # to create AdamW optimizer

import matplotlib.pyplot as plt

tf.get_logger().setLevel('ERROR')

ModuleNotFoundError: No module named 'tensorflow_text'

In [84]:
import pandas as pd
import json

In [7]:
with open('data/s/train_s.jsonl', 'r') as f:
  a = list(f)

data_s =[]
for element in a:
  data_s.append(json.loads(element))

data_s = pd.DataFrame(data_s)

In [8]:
data_s

qID  \
0    3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-2   
1    3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1   
2    3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-1   
3    3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-2   
4    3D5G8J4N5CI2K40F4RZLF9OG2CKVTH-2   
..                                ...   
635  3EGKVCRQFY6JSC139GVKMEMPGCSBY6-1   
636  3566S7OX5FXZ0UNAKACV3PPIOHJ17V-2   
637  3566S7OX5FXZ0UNAKACV3PPIOHJ17V-1   
638  3HEM8MA6H9AXTFCKHDKRCE03806PQT-1   
639  3HEM8MA6H9AXTFCKHDKRCE03806PQT-2   

                                              sentence option1    option2  \
0    Ian volunteered to eat Dennis's menudo after a...     Ian     Dennis   
1    Ian volunteered to eat Dennis's menudo after a...     Ian     Dennis   
2    He never comes to my home, but I always go to ...    home      house   
3    He never comes to my home, but I always go to ...    home      house   
4    Kyle doesn't wear leg warmers to bed, while Lo...    Kyle      Logan   
..                                                 ...     ...        ...   
635  Carrie needed to be vigilant about her bone he...  Carrie    Natalie   
636  The waves destroyed the garage but left the ho...  garage      house   
637  The waves destroyed the garage but left the ho...  garage      house   
638  The science student tried using the telescope ...  galaxy  telescope   
639  The science student tried using the telescope ...  galaxy  telescope   

    answer  
0        2  
1        1  
2        1  
3        2  
4        2  
..     ...  
635      1  
636      2  
637      1  
638      1  
639      2  

[640 rows x 5 columns]

In [94]:
def create_labeled_pairs(sentence,option1,option2,answer):
    pairs = [ sentence.replace('_',option) for option in [option1,option2]]
    dico = {}
    if int(answer) == 1:
        dico[True] = pairs[0]
        dico[False] = pairs[1]
    elif int(answer) ==2 :
        dico[True] = pairs[1]
        dico[False]=pairs[0]
    return dico

In [95]:
df = pd.DataFrame()
for ind in range(len(data_s)):
    dico = create_labeled_pairs(data_s['sentence'][ind],data_s['option1'][ind],
                                data_s['option2'][ind],data_s['answer'][ind]).items()
    df = pd.concat([df, pd.DataFrame(dico)],axis=0)
df.columns = ['category','text']
df

category                                               text
0       True  Ian volunteered to eat Dennis's menudo after a...
1      False  Ian volunteered to eat Dennis's menudo after a...
0       True  Ian volunteered to eat Dennis's menudo after a...
1      False  Ian volunteered to eat Dennis's menudo after a...
0       True  He never comes to my home, but I always go to ...
..       ...                                                ...
1      False  The waves destroyed the garage but left the ho...
0       True  The science student tried using the telescope ...
1      False  The science student tried using the telescope ...
0       True  The science student tried using the telescope ...
1      False  The science student tried using the telescope ...

[1280 rows x 2 columns]

In [57]:
#df['Label'] = df['Label'].astype(int)
#df

In [58]:
df = df.sample(frac=1)
df

category                                               text
1      False  The idea was given to Steven to mull over and ...
1      False  Jessica was fatter than Rebecca because Rebecc...
1      False  Elena told Natalie to put the hood of her jack...
1      False  Mary is sending an important package to Sarah,...
1      False  My sister enjoyed writing on the blog more tha...
..       ...                                                ...
1      False  Rebecca picked up Amy to carpool to work every...
1      False  Matthew offered to help write a fitness plan f...
1      False  Kevin didn't consider the costs when they boug...
1      False  Dennis gave his hammer to Robert so he could h...
0       True  Derrick was unable to stay focused at work unl...

[1280 rows x 2 columns]

In [50]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

example_text = 'I will watch Memento tonight'
bert_input = tokenizer(example_text,padding='max_length', max_length = 10,
                       truncation=True, return_tensors="pt")


print(bert_input['input_ids'])
print(bert_input['token_type_ids'])
print(bert_input['attention_mask'])

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

tensor([[  101,   146,  1209,  2824,  2508, 26173,  3568,   102,     0,     0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])


In [51]:
example_text = tokenizer.decode(bert_input.input_ids[0])

print(example_text)

[CLS] I will watch Memento tonight [SEP] [PAD] [PAD]


In [66]:
import torch
import numpy as np
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
labels = {'False':0,
          'True':1}

class Dataset(torch.utils.data.Dataset):

    def __init__(self, df):

        self.labels = [labels[label] for label in df['category']]
        self.texts = [tokenizer(text,
                               padding='max_length', max_length = 512, truncation=True,
                                return_tensors="pt") for text in df['text']]

    def classes(self):
        return self.labels

    def __len__(self):
        return len(self.labels)

    def get_batch_labels(self, idx):
        # Fetch a batch of labels
        return np.array(self.labels[idx])

    def get_batch_texts(self, idx):
        # Fetch a batch of inputs
        return self.texts[idx]

    def __getitem__(self, idx):

        batch_texts = self.get_batch_texts(idx)
        batch_y = self.get_batch_labels(idx)

        return batch_texts, batch_y

In [67]:
np.random.seed(112)
df_train, df_val, df_test = np.split(df.sample(frac=1, random_state=42),
                                     [int(.8*len(df)), int(.9*len(df))])

print(len(df_train),len(df_val), len(df_test))

1024 128 128


In [68]:
from torch import nn
from transformers import BertModel

class BertClassifier(nn.Module):

    def __init__(self, dropout=0.5):

        super(BertClassifier, self).__init__()

        self.bert = BertModel.from_pretrained('bert-base-cased')
        self.dropout = nn.Dropout(dropout)
        self.linear = nn.Linear(768, 2)
        self.relu = nn.ReLU()

    def forward(self, input_id, mask):

        _, pooled_output = self.bert(input_ids= input_id, attention_mask=mask,return_dict=False)
        dropout_output = self.dropout(pooled_output)
        linear_output = self.linear(dropout_output)
        final_layer = self.relu(linear_output)

        return final_layer

In [69]:
from torch.optim import Adam
from tqdm import tqdm

def train(model, train_data, val_data, learning_rate, epochs):

    train, val = Dataset(train_data), Dataset(val_data)

    train_dataloader = torch.utils.data.DataLoader(train, batch_size=2, shuffle=True)
    val_dataloader = torch.utils.data.DataLoader(val, batch_size=2)

    use_cuda = torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")

    criterion = nn.CrossEntropyLoss()
    optimizer = Adam(model.parameters(), lr= learning_rate)

    if use_cuda:

            model = model.cuda()
            criterion = criterion.cuda()

    for epoch_num in range(epochs):

            total_acc_train = 0
            total_loss_train = 0

            for train_input, train_label in tqdm(train_dataloader):

                train_label = train_label.to(device)
                mask = train_input['attention_mask'].to(device)
                input_id = train_input['input_ids'].squeeze(1).to(device)

                output = model(input_id, mask)

                batch_loss = criterion(output, train_label.long())
                total_loss_train += batch_loss.item()

                acc = (output.argmax(dim=1) == train_label).sum().item()
                total_acc_train += acc

                model.zero_grad()
                batch_loss.backward()
                optimizer.step()

            total_acc_val = 0
            total_loss_val = 0

            with torch.no_grad():

                for val_input, val_label in val_dataloader:

                    val_label = val_label.to(device)
                    mask = val_input['attention_mask'].to(device)
                    input_id = val_input['input_ids'].squeeze(1).to(device)

                    output = model(input_id, mask)

                    batch_loss = criterion(output, val_label.long())
                    total_loss_val += batch_loss.item()

                    acc = (output.argmax(dim=1) == val_label).sum().item()
                    total_acc_val += acc

            print(
                f'Epochs: {epoch_num + 1} | Train Loss: {total_loss_train / len(train_data): .3f} \
                | Train Accuracy: {total_acc_train / len(train_data): .3f} \
                | Val Loss: {total_loss_val / len(val_data): .3f} \
                | Val Accuracy: {total_acc_val / len(val_data): .3f}')

In [77]:
EPOCHS = 5
model = BertClassifier()
LR = 1e-6

train(model, df_train, df_val, LR, EPOCHS)C

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


KeyError: False

In [82]:
[labels[label] for label in df['category']]

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,


## Autre version de test

In [85]:
df

category                                               text
0      True  Ian volunteered to eat Dennis's menudo after a...
1     False  Ian volunteered to eat Dennis's menudo after a...
0      True  Ian volunteered to eat Dennis's menudo after a...
1     False  Ian volunteered to eat Dennis's menudo after a...
0      True  He never comes to my home, but I always go to ...
..      ...                                                ...
1     False  The waves destroyed the garage but left the ho...
0      True  The science student tried using the telescope ...
1     False  The science student tried using the telescope ...
0      True  The science student tried using the telescope ...
1     False  The science student tried using the telescope ...

[1280 rows x 2 columns]

In [92]:
df['category'] = df['category'].apply(bool())

TypeError: 'bool' object is not callable

In [93]:
bool('True')

True

In [114]:
df2 = df
df2.columns = ['label','sentence']
df2['label'] = df2['label'].astype(int)
sentences=df2.sentence.values
labels = df2.label.values

In [115]:
df2
sentences

array(["Ian volunteered to eat Dennis's menudo after already having a bowl because Dennis despised eating intestine.",
       "Ian volunteered to eat Dennis's menudo after already having a bowl because Ian despised eating intestine.",
       "Ian volunteered to eat Dennis's menudo after already having a bowl because Ian enjoyed eating intestine.",
       ...,
       'The science student tried using the telescope to see the galaxy but the telescope was too far.',
       'The science student tried using the telescope to see the galaxy but the telescope was too weak.',
       'The science student tried using the telescope to see the galaxy but the galaxy was too weak.'],
      dtype=object)

In [116]:
from transformers import BertTokenizer
# using the low level BERT for our task.
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

# Printing the original sentence.
print(' Original: ', sentences[0])

# Printing the tokenized sentence in form of list.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids.
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

 Original:  Ian volunteered to eat Dennis's menudo after already having a bowl because Dennis despised eating intestine.
Tokenized:  ['ian', 'volunteered', 'to', 'eat', 'dennis', "'", 's', 'menu', '##do', 'after', 'already', 'having', 'a', 'bowl', 'because', 'dennis', 'despised', 'eating', 'int', '##est', '##ine', '.']
Token IDs:  [4775, 14382, 2000, 4521, 6877, 1005, 1055, 12183, 3527, 2044, 2525, 2383, 1037, 4605, 2138, 6877, 26626, 5983, 20014, 4355, 3170, 1012]


In [117]:
input_ids = []
for sent in sentences:
    # so basically encode tokenizing , mapping sentences to thier token ids after adding special tokens.
    encoded_sent = tokenizer.encode(
                        sent,                      # Sentence which are encoding.
                        add_special_tokens = True, # Adding special tokens '[CLS]' and '[SEP]'

                         )


    input_ids.append(encoded_sent)

In [118]:
from keras_preprocessing.sequence import pad_sequences

MAX_LEN = 128

input_ids = pad_sequences(input_ids, maxlen=MAX_LEN , truncating="post", padding="post")

In [119]:
attention_masks = []

for sent in input_ids:

    # Generating attention mask for sentences.
    #   - when there is 0 present as token id we are going to set mask as 0.
    #   - we are going to set mask 1 for all non-zero positive input id.
    att_mask = [int(token_id > 0) for token_id in sent]


    attention_masks.append(att_mask)

In [128]:
np.shape(attention_masks) ,

(1280, 128)

In [129]:
from sklearn.model_selection import train_test_split

train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(input_ids, labels,
                                                                                    test_size=0.2)
train_masks, validation_masks, _, _ = train_test_split(attention_masks,
                                                       labels,test_size=0.2)

In [130]:
#changing the numpy arrays into tensors for working on GPU.
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)

train_labels = torch.tensor(train_labels)
validation_labels = torch.tensor(validation_labels)

train_masks = torch.tensor(train_masks)
validation_masks = torch.tensor(validation_masks)

from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

# Deciding the batch size for training.

batch_size = 32

#DataLoader for our training set.
train_data = TensorDataset(train_inputs, train_masks, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

# DataLoader for our validation(test) set.
validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)

In [133]:
from transformers import BertForSequenceClassification, AdamW, BertConfig


model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels = 2,
    output_attentions = False,
    output_hidden_states = False,
)

# Running the model on GPU.
#model.cuda()

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [134]:
optimizer = AdamW(model.parameters(),
                  lr = 2e-5,
                  eps = 1e-8
                )

c:\users\marti\work\lattice-internship\venv\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [136]:
from transformers import get_linear_schedule_with_warmup

# Number of training epochs (authors recommend between 2 and 4)
epochs = 4

# Total number of training steps is number of batches * number of epochs.
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(optimizer,
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

In [140]:
import torch
import time
# If there's a GPU available...
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

No GPU available, using the CPU instead.


In [141]:
loss_values = []

for epoch_i in range(0, epochs):
    t0 = time.time()

    total_loss = 0
    # putting model in traing mode there are two model eval and train for model
    model.train()


    for step, batch in enumerate(train_dataloader):

        #checking time taken after every 50 steps.
        if step % 50 == 0 and not step == 0:
            elapsed = format_time(time.time() - t0)

        #getting ids,mask,labes for every batch
        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_labels = batch[2].to(device)


        outputs = model(b_input_ids,
                    token_type_ids=None,
                    attention_mask=b_input_mask,
                    labels=b_labels)

        loss = outputs[0]

        total_loss += loss.item()

        # doing back propagation
        loss.backward()

        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    avg_train_loss = total_loss / len(train_dataloader)

RuntimeError: expected scalar type Long but found Int